### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by Kafkamorph** [yakkomajuri/leavemealone-extension#1]
![Screenshot 2020-05-12 at 11 35 18](https://user-images.githubusercontent.com/2609870/81674448-17bae500-9445-11ea-89aa-b473ba8f405f.png)

As per the screenshot - a domain not in the vetted list being marked as malicious.

**Comment by yakkomajuri** [comment]
Interesting - I'm unable to reproduce it but will look into it. Version 0.0.2 should be coming out and that included a reference to the flagged domain in the alert ("... marked the domain xxxxxx.com as potentially malicious..."), which should make debugging this easier.

I nevertheless modified most of the code for v0.0.3 so hopefully this will be fixed. I have a hunch it has to do with the fallback mechanism for the failure to get the list of domains correctly. I was implementing `chrome.storage.local.get` incorrectly. If that's the case, 0.0.3 should fix it.

Thank you for this!

**Comment by yakkomajuri** [comment]
@Kafkamorph Version 0.0.3 is out - could you try that out and see if it gives you any false positives? I haven't yet gotten any.

**Comment by Kafkamorph** [comment]
Hi @yakkomajuri .
Just installed the latest version, and went back to the site that was previously being blocked (https://www.bootsphoto.com/), and it's working perfectly now.

Cheers! 👍

**Comment by yakkomajuri** [comment]
Yeah actually I realized it has nothing to do with the website being "blocked". I managed to (accidentally) reproduce it. The bug is still present in v0.0.3 and had something to do with when a frame loads even though the website loaded much earlier. It happened to me once I opened up my browser after the laptop was on standby. Thankfully it alerts the name of the domain now so I could see it was empty. 

For v0.0.4 I added a check prior to the alarm to assert the domain isn't `null`, `undefined`, or an empty string. That should do it if something goes wrong and the domain name is empty.
